export const ELE_HELLO = 'hey there friend';

/* Two hundred. Written to be said out loud by somebody who is on your side
   and has all the time in the world. */
export const ELE_QUOTES = [
  'i believe in you pal',
  'we ALL believe in you',
  'ur a winner kiddo. don\'t you ever forget it',
  'i need you to be the person i know you can be',
  'don\'t leave anything out to chance',
  'you\'re doing better than you think you are',
  'i\'m proud of you. i don\'t say that lightly',
  'rest is not quitting, friend',
  'you don\'t have to have it figured out today',
  'the hard part is not forever',
  'you have survived every single one of your worst days',
  'take the small step. the small step counts',
  'i know it\'s heavy. put it down for a minute',
  'you are not behind. there is no schedule',
  'somebody is glad you\'re here. i\'m somebody',
  'be as kind to you as you are to everybody else',
  'you don\'t owe anyone a perfect version of you',
  'it\'s okay if today was just about getting through it',
  'you\'re allowed to start over as many times as you need',
  'the fact that you\'re still trying says everything',
  'i see how hard you\'re working. even if nobody else does',
  'you\'re not too much. you never were',
  'you\'re not a burden, kiddo. you\'re a person',
  'slow progress is still progress. i\'d know',
  'drink some water. i mean it',
  'eat something. you\'ll think clearer after',
  'go outside for ten minutes. the sky is still there',
  'call the person you\'ve been meaning to call',
  'you\'re allowed to ask for help. that\'s what it\'s for',
  'nobody good ever did it alone. nobody',
  'your best today doesn\'t have to look like your best last year',
  'you\'re allowed to be proud of the small ones',
  'i remember when you couldn\'t do this at all',
  'look how far you came. actually stop and look',
  'you\'re going to be okay. maybe not today. but you are',
  'one thing at a time. just the one',
  'you don\'t have to win. you just have to keep showing up',
  'the mess is part of it, pal. it always was',
  'you\'re allowed to change your mind',
  'quitting the wrong thing is not quitting',
  'you can be scared and do it anyway. most people are',
  'courage is just doing it while your hands shake',
  'the doubt doesn\'t mean you\'re wrong. it means you care',
  'you\'re not lazy. you\'re tired. those are not the same thing',
  'give yourself the grace you hand out to everyone else for free',
  'i\'d pick you for my team every single time',
  'you are worth the effort it takes to be you',
  'it\'s okay to want more. that\'s not greed, that\'s being alive',
  'you don\'t have to earn the right to rest',
  'tomorrow gets a fresh page. that is the whole point of tomorrow',
  'hey. breathe. all the way out',
  'shoulders down. jaw loose. there you go',
  'you\'ve been holding your breath again. let it go',
  'whatever it is, it is smaller than it was at three in the morning',
  'sleep on it. it looks different in the morning. it always does',
  'you\'re doing a hard thing. of course it feels hard',
  'it\'s supposed to be hard. that\'s how you know it counts',
  'i never said it would be easy. i said you could do it',
  'don\'t compare your middle to somebody else\'s ending',
  'they had help too. everybody had help',
  'you don\'t have to be the strongest. just be honest',
  'tell somebody how you actually are today',
  'the people who love you want the real one, not the tidy one',
  'you are easier to love than you think you are',
  'somebody would miss you terribly. never doubt that',
  'you make a difference you will never get to see',
  'the kindness you gave out is still working somewhere',
  'that thing you did for them? they still think about it',
  'you\'re better at this than you were, and that is the whole game',
  'skill is just practice wearing a nicer coat',
  'it is not too late. it has never once been too late',
  'start ugly. ugly finishes. perfect never starts',
  'done beats perfect. ask anybody who ever finished anything',
  'the first draft is allowed to be bad. that is its job',
  'you learn it by doing it badly first. everyone does',
  'failing at it is how you find out where it bends',
  'you\'re not broken. you\'re between things',
  'you\'re allowed to not know yet',
  'not knowing is where every good thing begins',
  'curiosity is a kind of hope, and you have got both',
  'you were curious about something once. go find it again',
  'make something today. anything. badly is fine',
  'the world is better with the things you put in it',
  'your taste is good. trust it',
  'do it your way. your way is the reason they would want it',
  'you don\'t need permission, pal',
  'nobody is coming to tell you it\'s your turn. it\'s your turn',
  'you\'re allowed to take up space',
  'say the thing. they probably want to hear it',
  'ask for it. the worst they say is no, and no is survivable',
  'you\'ve been told no before and you are still standing',
  'rejection is a redirect with bad manners. nothing more',
  'it wasn\'t a waste. you know things now that you didn\'t',
  'you\'d forgive a friend for this in a second. be your friend',
  'talk to yourself the way you would talk to me',
  'you are not the worst thing you ever did',
  'that was then. you\'re here now',
  'people can change. you already have. twice',
  'i have watched you grow. i am not making that up',
  'keep going. i\'ll be right here',
  'you don\'t have to feel good to do good',
  'some days it is enough to just not make it worse',
  'surviving is a legitimate use of a day',
  'put the phone down and look at something far away',
  'stretch. right now. i\'ll wait',
  'you\'ve been sitting too long, friend',
  'go to bed. it will keep till morning',
  'it is not a character flaw to need a nap',
  'you\'re allowed to have an easy day',
  'clear one small thing. just one. watch what it does',
  'make the bed. it\'s a promise you keep to yourself',
  'wash the one dish. it was never about the dish',
  'open a window. new air helps more than it should',
  'put on the song you loved when you were fifteen',
  'dance badly where nobody can see. it works',
  'laugh at something stupid today. doctor\'s orders',
  'you\'re allowed to enjoy things without earning them first',
  'joy is not a reward. it is a supply',
  'take the picture. you will want it later',
  'write it down. future you is going to be so grateful',
  'you are going to be somebody\'s good memory',
  'be gentle. everybody is carrying something',
  'you never know what their day looked like before you got there',
  'give them the benefit of the doubt. save some for you',
  'you can be right or you can be kind. mostly pick kind',
  'apologise fast, mean it, and move on',
  'forgive somebody today. you can start with you',
  'hold the grudge lighter. it\'s heavy and it\'s yours to carry',
  'let it go. not because they deserve it. because you do',
  'you don\'t have to attend every argument you are invited to',
  'some people are weather. you are not the reason it rains',
  'you can love somebody and still need the distance',
  'no is a full sentence, kiddo',
  'protect your quiet. it isn\'t selfish, it\'s maintenance',
  'you\'re allowed to leave the room',
  'you don\'t have to explain yourself to everyone who asks',
  'you can outgrow people who were exactly right for you once',
  'the right ones will still be there when you look up',
  'reach out first. it is almost never the wrong call',
  'tell them you love them. out loud. today',
  'you are somebody\'s favourite person. probably more than one',
  'i\'d sit with you on a bad day. no talking required',
  'you don\'t have to be interesting to be wanted',
  'just being there is most of it',
  'show up. that\'s ninety percent of love',
  'keep the promise you made yourself in january',
  'or don\'t. and make a better one instead',
  'the plan is allowed to change. you don\'t have to',
  'you\'re allowed a whole new dream',
  'wanting a different life doesn\'t mean you wasted this one',
  'it isn\'t starting over. it\'s carrying everything forward',
  'everything you learned comes with you. all of it',
  'nothing is wasted. not one bit of it',
  'you are more prepared than you feel',
  'the you from five years ago would be amazed at this',
  'tell yourself the good thing. out loud is better',
  'you\'re doing fine, pal. genuinely',
  'i\'m not just saying it. i don\'t do that',
  'you don\'t need fixing. you are not a machine',
  'the goal isn\'t to feel nothing. it\'s to feel it and stay',
  'big feelings mean a big heart. that is the whole trade',
  'crying is your body doing maintenance. let it work',
  'you\'re allowed to be sad about it for as long as it takes',
  'grief is love with nowhere to go. give it somewhere to go',
  'it gets lighter. not smaller. lighter',
  'you will laugh again, and it will surprise you when it happens',
  'the good days come back. they always come back',
  'hold on till morning. just till morning',
  'tell one person. that is the whole ask',
  'there is help, and it is not weakness to take it',
  'you have made it through one hundred percent of this so far',
  'the odds are on you. look at the record',
  'hope is not naive. it\'s a decision you make again tomorrow',
  'keep a little hope back for yourself. don\'t give it all away',
  'you\'re allowed to want good things for you',
  'good things happen to people like you. that is not a joke',
  'luck finds the ones who kept going. so keep going',
  'you are closer than you were. that is always true',
  'the door opens on the last push. it usually does',
  'finish it. even messy. finish it',
  'you started. that is the rare part',
  'most people never start, kiddo. you did',
  'be stubborn about the goal and loose about the route',
  'if the plan isn\'t working, change the plan. not the dream',
  'take the long way, if the long way is the one you can walk',
  'slow is fine. stopped is fine too, as long as you start again',
  'rest and then go. in that order',
  'don\'t wait to feel ready. ready comes after, not before',
  'confidence is something you build. not something you find',
  'do it scared. that one counts double',
  'brave is not loud. usually brave is just a tuesday',
  'nobody is watching as closely as you think. go be silly',
  'you\'re allowed to be a beginner at forty. or eighty',
  'it is your one life. spend it on what you actually like',
  'you\'re not running late. this is just how long yours takes',
  'i\'ve got all the time in the world for you',
  'come back and see me whenever. i\'m always here',
  'take care of yourself out there, friend',
  'whatever happens today, you are still you, and that is enough',
  'i\'ll say it as many times as you need. i believe in you'
];
export const ELE_PLACES = [
  { id: 'sol',    name: 'THE SUNFLOWER FIELD', song: 'first', mote: 14, shade: 2 },
  { id: 'oase',   name: 'THE OASIS',           song: 'wide',  mote: 15, shade: 6 },
  { id: 'fjell',  name: 'THE MOUNTAIN FIELD',  song: 'carry', mote: 15, shade: 2 },
  { id: 'sky',    name: 'UP IN THE CLOUDS',    song: 'above', mote: 15, shade: 7 },
  { id: 'tempel', name: 'THE THIRD TEMPLE',    song: 'home',  mote: 14, shade: 8 }
];

/* ---- 31.2 five songs -----------------------------------------------------
   Not lullabies. Every one of them is in a major key, every one climbs, and
   every one lands somewhere brighter than it started — this is meant to feel
   like waking up rather than going under. Same shape as everything else that
   makes noise in here: [note, start in sixteenths, length in sixteenths].
   ========================================================================== */
export const ELE_HZ = {
  C2:65.41, D2:73.42, E2:82.41, F2:87.31, Fs2:92.50, G2:98.00, A2:110.00, B2:123.47,
  C3:130.81, Cs3:138.59, D3:146.83, Ds3:155.56, E3:164.81, F3:174.61, Fs3:185.00,
  G3:196.00, Gs3:207.65, A3:220.00, B3:246.94,
  C4:261.63, Cs4:277.18, D4:293.66, Ds4:311.13, E4:329.63, F4:349.23, Fs4:369.99,
  G4:392.00, Gs4:415.30, A4:440.00, B4:493.88,
  C5:523.25, Cs5:554.37, D5:587.33, Ds5:622.25, E5:659.26, F5:698.46, Fs5:739.99,
  G5:783.99, Gs5:830.61, A5:880.00, B5:987.77, C6:1046.50
};

export const ELE_SONGS = {
  /* FIRST LIGHT — D major, I V vi IV, the lead climbing a fourth each phrase */
  first: { bpm: 76, len: 32,
    lead: [['D4',0,4],['Fs4',4,2],['A4',6,2],['B4',8,4],['A4',12,4],
           ['Fs4',16,2],['A4',18,2],['D5',20,4],['Cs5',24,2],['B4',26,2],['A4',28,4]],
    bass: [['D2',0,8],['A2',8,8],['B2',16,8],['G2',24,8]],
    pad:  [['D4',0,8],['Fs4',0,8],['A4',0,8],['Cs4',8,8],['E4',8,8],['A4',8,8],
           ['B3',16,8],['D4',16,8],['Fs4',16,8],['B3',24,8],['D4',24,8],['G4',24,8]],
    arp:  [['D5',0,1],['A4',2,1],['Fs4',4,1],['A4',6,1],['E5',8,1],['Cs5',10,1],['A4',12,1],['Cs5',14,1],
           ['Fs5',16,1],['D5',18,1],['B4',20,1],['D5',22,1],['D5',24,1],['B4',26,1],['G4',28,1],['B4',30,1]] },

  /* WIDE — A major, open fifths, the slowest of the five and the least busy */
  wide: { bpm: 66, len: 32,
    lead: [['A4',0,6],['B4',6,2],['Cs5',8,6],['B4',14,2],['A4',16,4],['Fs4',20,4],['E4',24,6],['A4',30,2]],
    bass: [['A2',0,8],['E3',8,8],['Fs3',16,8],['D3',24,8]],
    pad:  [['A3',0,8],['E4',0,8],['E3',8,8],['B3',8,8],['Fs3',16,8],['Cs4',16,8],['D3',24,8],['A3',24,8]],
    arp:  [['E5',0,2],['Cs5',4,2],['A4',8,2],['Cs5',12,2],['B4',16,2],['Gs4',20,2],['E4',24,2],['A4',28,2]] },

  /* CARRY — G major, a bass that actually walks, the warmest of them */
  carry: { bpm: 84, len: 32,
    lead: [['G4',0,4],['A4',4,2],['B4',6,2],['D5',8,4],['B4',12,4],
           ['A4',16,2],['B4',18,2],['D5',20,2],['E5',22,2],['D5',24,4],['G4',28,4]],
    bass: [['G2',0,2],['B2',2,2],['D3',4,2],['G3',6,2],['D3',8,2],['Fs3',10,2],['A3',12,2],['D3',14,2],
           ['E3',16,2],['G3',18,2],['B3',20,2],['E3',22,2],['C3',24,2],['E3',26,2],['G3',28,2],['C3',30,2]],
    pad:  [['G3',0,8],['B3',0,8],['D4',0,8],['Fs3',8,8],['A3',8,8],['D4',8,8],
           ['E3',16,8],['G3',16,8],['B3',16,8],['C4',24,8],['E4',24,8],['G4',24,8]],
    arp:  [['G5',0,1],['D5',3,1],['B4',6,1],['D5',9,1],['A5',12,1],['Fs5',15,1],['D5',18,1],
           ['B4',21,1],['E5',24,1],['C5',27,1],['G4',30,1]] },

  /* ABOVE — E major, suspended, everything an octave higher than it needs */
  above: { bpm: 70, len: 32,
    lead: [['B4',0,4],['E5',4,4],['Fs5',8,2],['E5',10,2],['B4',12,4],
           ['Gs4',16,4],['B4',20,4],['Cs5',24,4],['E5',28,4]],
    bass: [['E2',0,8],['B2',8,8],['Cs3',16,8],['A2',24,8]],
    pad:  [['E3',0,8],['Gs3',0,8],['B3',0,8],['B3',8,8],['Ds4',8,8],['Fs4',8,8],
           ['Cs4',16,8],['E4',16,8],['Gs4',16,8],['A3',24,8],['Cs4',24,8],['E4',24,8]],
    arp:  [['E5',0,1],['B4',2,1],['Gs4',4,1],['B4',6,1],['Fs5',8,1],['Ds5',10,1],['B4',12,1],['Ds5',14,1],
           ['Gs5',16,1],['E5',18,1],['Cs5',20,1],['E5',22,1],['E5',24,1],['Cs5',26,1],['A4',28,1],['Cs5',30,1]] },

  /* HOME — C major, a hymn, and the only one that ends where it started */
  home: { bpm: 80, len: 32,
    lead: [['C5',0,4],['B4',4,2],['A4',6,2],['G4',8,4],['E4',12,4],
           ['F4',16,2],['G4',18,2],['A4',20,4],['G4',24,2],['E4',26,2],['C5',28,4]],
    bass: [['C3',0,8],['G2',8,8],['A2',16,8],['F2',24,8]],
    pad:  [['C4',0,8],['E4',0,8],['G4',0,8],['B3',8,8],['D4',8,8],['G4',8,8],
           ['A3',16,8],['C4',16,8],['E4',16,8],['F3',24,8],['A3',24,8],['C4',24,8]],
    arp:  [['C5',0,2],['G4',4,2],['E4',8,2],['G4',12,2],['D5',16,2],['B4',20,2],['G4',24,2],['C5',28,2]] }
};
